services:
  slurmjupyter:
        image: jupyter
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        volumes:
                - /home/pat_zamora:/home/pat_zamora
                - /opt:/opt
        ports:
                - 8888:8889
        cpus: 2
        mem_limit: 10000M

        entrypoint: ["/bin/bash", "-c",
                                 "service munge start &&
                                 adduser -u 182000020 pat_zamora --disabled-password --gecos ' ' &&
                                 su - pat_zamora -c 'conda clean -iy' &&
                                 su - pat_zamora -c 'jupyter lab --ip 0.0.0.0 --allow-root --notebook-dir=/home/pat_zamora --no-browser --NotebookApp.token='' --NotebookApp.password='tanongmokaykarisse''"]

